const $ = selector => document.querySelector(selector);
const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => Number(value || 0).toLocaleString('nl-BE');
const date = value => value ? new Date(value).toLocaleString('nl-BE',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Brussels'}) : '—';
const state = {session:null,data:null,guild:null,page:'overview',search:'',filter:'all',busy:false};
const paths = {
  overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
  tickets:'M3 5h18v4a3 3 0 0 0 0 6v4H3v-4a3 3 0 0 0 0-6z M14 5v14',
  applications:'M6 3h12v18H6z M9 7h6 M9 11h6 M9 15h4',
  transcripts:'M5 3h10l5 5v13H5z M15 3v6h5 M8 13h8 M8 17h6',
  warnings:'m12 3 10 18H2z M12 9v5 M12 17v1',
  members:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3 M9 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M17 4a4 4 0 0 1 0 7 M22 21v-3a4 4 0 0 0-4-4',
  games:'M5 8h14l3 11h-5l-3-3h-4l-3 3H2z M7 10v5 M4.5 12.5h5 M17 11v1 M19 14v1',
  information:'M12 2a10 10 0 1 0 0 20a10 10 0 0 0 0-20 M12 11v6 M12 7v1',
  settings:'m12 2 2 3 4-1 1 4 3 2-3 3 1 4-4 1-2 3-3-3-4 1-1-4-3-2 3-3-1-4 4-1z M12 8a4 4 0 1 0 0 8a4 4 0 0 0 0-8',
  activity:'M3 12h4l3-8 4 16 3-8h4'
  ,planning:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 11h16'
  ,promotions:'m4 12 8-8 8 8 M8 12v8h8v-8'
  ,gangpot:'M3 6h18v14H3z M3 10h18 M16 14h3 M7 2h10v4'
};
const pages = {
  overview:['Overzicht','Een blik op alles wat er speelt.'], tickets:['Tickets','Beheer vragen, gesprekken en afgehandelde tickets.'],
  applications:['Sollicitaties','Van eerste contact tot de familie.'], transcripts:['Transcripts','Gesprekken bewaren, terugvinden en bekijken.'],
  warnings:['Gangwarns','Duidelijke afspraken. Een blijvende historie.'], members:['Leden & rangen','Iedereen op de juiste plek binnen Legion.'],
  games:['Games & coins','Fun-commands, saldi en de economie van je server.'], information:['Informatie','Jouw teksten, regels en Legion-identiteit.'],
  settings:['Instellingen','De basis voor een goed georganiseerde gang.'], activity:['Activiteit','Wat er gebeurde, wanneer en door wie.']
  ,planning:['Planning','Voorbereiden, verzamelen en aanwezigheid bijhouden.']
  ,promotions:['Promotievoorstellen','Een hogere rang, met beoordeling door de leiding.']
  ,gangpot:['Gangpot','Betaalmeldingen, Lead-vinkjes en het bevestigde in-game saldo.']
  ,absences:['Afmeldingen','Aanvragen, goedkeuringen en vrijstellingen per week.']
  ,health:['Botstatus','Verbinding en acties die op herhaling wachten.']
  ,modules:['Modules instellen','Bedragen, tijden, kanalen en gedrag van de bot.']
  ,collection:['Vangstenboek','Visverzamelingen en wekelijkse challenges.']
};
const labels = {open:'Open',accepted:'Aangenomen',rejected:'Afgewezen',closed:'Gesloten',failed:'Mislukt',pending:'In wachtrij',sent:'DM verzonden',joined:'Gejoind',claimed:'Invite opgehaald',dm_blocked:'DM geblokkeerd',expired:'Verlopen',revoked:'Ingetrokken',ready:'In verwerking',done:'Opgeslagen',unavailable:'Niet beschikbaar',approved:'Goedgekeurd',approving:'Wordt verwerkt',cancelled:'Geannuleerd',ended:'Afgelopen'};
const badge = status => `<span class="badge ${['accepted','approved','sent','joined','claimed','done'].includes(status)?'green':['open','pending','approving','ready','expired','dm_blocked'].includes(status)?'orange':['rejected','cancelled','failed','revoked','unavailable'].includes(status)?'red':'gray'}">${e(labels[status] || status)}</span>`;
const icon = key => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[key] || paths.overview}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const initials = name => e(String(name||'L').trim().split(/\s+/).map(word=>word[0]).slice(0,2).join('').toUpperCase());
function photo(url,name) { let safe=false; try { const parsed=new URL(url); safe=parsed.protocol==='https:' && ['cdn.discordapp.com','media.discordapp.net'].includes(parsed.hostname); }catch{} return safe ? `<img src="${e(url)}" alt="" loading="lazy" referrerpolicy="no-referrer">` : `<span class="initials">${initials(name)}</span>`; }
const person = (name,id,avatar) => `<div class="person">${photo(avatar,name)}<div><strong>${e(name)}</strong><small>${e(id)}</small></div></div>`;
const empty = (title,text='Er staat hier nog niets. Nieuwe gegevens verschijnen automatisch.') => `<div class="empty"><strong>${e(title)}</strong><p>${e(text)}</p></div>`;
const card = (title,subtitle,body,extra='') => `<section class="card"><div class="card-header"><div><h2>${e(title)}</h2>${subtitle?`<p>${e(subtitle)}</p>`:''}</div>${extra}</div>${body}</section>`;
const table = (headers,rows) => rows.length ? `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : empty('Geen resultaten','Pas je filters aan of wacht op nieuwe gegevens.');
const btn = (label,action,attrs='',style='secondary') => `<button type="button" class="${style} tiny" data-action="${e(action)}" ${attrs}>${e(label)}</button>`;
const link = (label,url,style='secondary') => `<a class="button ${style} tiny" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`;
function toast(text,error=false) { const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{el.hidden=true;},6500); }
async function api(path,body) {
  const response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-CSRF-Token':state.session?.csrf || ''}:{},...(body?{body:JSON.stringify(body)}:{})});
  const value=await response.json(); if(!response.ok){ const error=new Error(value.error || 'De verbinding is tijdelijk niet beschikbaar.');error.status=response.status;throw error; } return value;
}
function showLogin(message='') { state.session=null;state.data=null;$('#loading').hidden=true;$('#app').hidden=true;$('#content').innerHTML='';$('#profile').innerHTML='';$('#login').hidden=false;$('#login-error').textContent=message;document.body.classList.remove('menu-open'); }
function navigation() {
  $('#navigation').innerHTML=Object.entries(pages).map(([key,[name]])=>`<button type="button" data-page="${key}" class="${state.page===key?'active':''}">${icon(key)}<span>${e(name)}</span>${key==='applications'&&state.data?.overview.openApplications?`<span class="nav-count">${number(state.data.overview.openApplications)}</span>`:key==='tickets'&&state.data?.overview.openTickets?`<span class="nav-count">${number(state.data.overview.openTickets)}</span>`:''}</button>`).join('');
}
async function load(render=true) {
  state.data=await api(`/api/dashboard/guilds/${state.guild}/summary`);
  $('#updated').textContent='Bijgewerkt '+new Date().toLocaleTimeString('nl-BE',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Brussels'});
  $('#connection').innerHTML='<i></i> Live'; if(render)renderPage();else navigation();
}
async function boot() {
  try {
    const code=new URLSearchParams(location.hash.slice(1)).get('login');
    if(code){history.replaceState(null,'','/dashboard');state.session=await api('/api/dashboard/login',{code});}
    else state.session=await api('/api/dashboard/session');
    state.guild=state.session.selectedGuild;
    $('#guild-select').innerHTML=state.session.guilds.map(guild=>`<option value="${e(guild.id)}">${e(guild.name)}</option>`).join('');$('#guild-select').value=state.guild;
    $('#profile').innerHTML=photo(state.session.user.avatar,state.session.user.name)+'<span class="profile-name">Leiding</span>';
    $('#loading').hidden=true;$('#login').hidden=true;$('#app').hidden=false;await load();
  }catch(error){showLogin(error.status===401?'':error.message);}
}
function quotaCard() {
  const q=state.data.overview.quota;
  if(!q)return card('Gangleden','Leden met de Legion-rol',`<div class="card-body"><div class="quota-number">${number(state.data.overview.legionMembers)}</div><p class="quota-note">De automatische ranglijst houdt je bezetting bij.</p><div class="progress"><span></span></div><button type="button" class="secondary tiny" data-page="members">Leden bekijken →</button></div>`,'<span class="badge green">Actief</span>');
  const color=q.icon==='🔴'?'red':q.icon==='🟠'||q.count===null?'orange':'green';
  return card('Sollicitatiestatus','De community bepaalt de beschikbare plaatsen',`<div class="card-body"><div class="quota-number">${q.count===null?'—':number(q.count)}<small>/ 25</small></div><div class="progress"><span style="width:${Math.min(100,((q.count||0)/25)*100)}%;background:var(--${color})"></span></div><p class="quota-note">${q.count===null?'De ledenstand wordt gecontroleerd.':q.full?'Solliciteren blijft mogelijk. Het bekijken van sollicitaties kan langer duren zolang Legion vol zit.':`${Math.max(0,25-q.count)} plekken beschikbaar voor de familie.`}</p><div class="quota-footer"><span>Minimale leeftijd: 16 jaar</span><span>Beperkte plaatsen vanaf 20</span></div></div>`,`<span class="badge ${color}">${e(q.label)}</span>`);
}
const activityNames = {'dashboard.settings':'Instellingen aangepast','coins.adjust':'Coins bijgewerkt','application.accepted':'Sollicitant aangenomen','application.rejected':'Sollicitatie afgewezen','application.closed':'Sollicitatie gesloten','application.reserve':'Sollicitatie geopend','application.dm.sent':'Aannamebericht verstuurd','application.interview':'Gesprek gestart','ticket.reserve':'Ticket geopend','ticket.closed':'Ticket gesloten','warning.add':'Gangwarn gegeven','warning.remove':'Gangwarn ingetrokken'};
function activityRows(items) { return items.length?items.map(item=>`<div class="activity-row"><span class="activity-dot">${item.event.includes('accepted')?'✓':item.event.includes('warning')?'!':'↗'}</span><div class="activity-main"><strong>${e(activityNames[item.event]||item.event)}</strong><p>${e(item.actor_name)}</p></div><span class="activity-time">${e(date(item.created_at))}</span></div>`).join(''):empty('Nog geen activiteit'); }
function overview() {
  const d=state.data,o=d.overview;
  const metrics=[['tickets','Open tickets',o.openTickets,'Vragen die op een antwoord wachten'],['applications','Sollicitaties',o.openApplications,'Dossiers die de leiding kan beoordelen'],['transcripts','Transcripts',o.savedTranscripts,'Veilig opgeslagen gesprekken'],['members','Gangleden',o.legionMembers,'Leden met de Legion-rol']];
  const recent=d.cases.filter(item=>item.status==='open').slice(0,5);
  return `<div class="welcome"><div><h2>Alles wat speelt, op één plek.</h2><p>${e(d.guild.name)} · Samen bouwen aan Legion.</p></div><span class="welcome-emblem">L</span></div><div class="metrics">${metrics.map(([key,title,value,note])=>`<section class="metric"><span class="metric-label">${e(title)}</span><span class="metric-icon">${icon(key)}</span><strong class="metric-number">${number(value)}</strong><span class="metric-detail">${e(note)}</span></section>`).join('')}</div>${o.pendingDMs?`<div class="notice orange">${number(o.pendingDMs)} aannamebericht(en) wachten op bezorging. Bekijk de uitnodigingsstatus bij Sollicitaties.</div>`:''}<div class="grid">${card('Open dossiers','Waar je leiding nodig is',recent.length?table(['Aanvrager','Type','Status',''],recent.map(item=>[person(item.owner_name,item.owner_id,item.owner_avatar),item.kind==='application'?'Sollicitatie':'Vraag',badge(item.status),btn('Bekijken','case.open',`data-id="${e(item.id)}"`)])):empty('Alles is bijgewerkt','Nieuwe vragen en sollicitaties verschijnen hier.'),btn('Panelen bijwerken','panel.refresh'))}${quotaCard()}</div><div class="grid">${card('Recente activiteit','De laatste handelingen van je team',`<div class="card-body">${activityRows(d.activity.slice(0,4))}</div>`)}${card('Botstatus','Verbonden met je Discord-server',`<div class="card-body"><div class="status-line"><span class="badge green">Online</span><span class="muted">Instellingen worden direct toegepast</span></div><div class="runtime"><div><strong>${number(Math.floor(o.uptime/60))} min</strong><span>Online sinds opstart</span></div><div><strong>${number(o.latency)} ms</strong><span>Discord-verbinding</span></div><div><strong>${number(o.memoryMB)} MB</strong><span>Botgeheugen</span></div></div><p class="muted" style="margin-top:16px">${o.pendingExports?`${number(o.pendingExports)} transcript(s) in de exportwachtrij.`:'De transcriptwachtrij is bijgewerkt.'}</p></div>`)}</div>`;
}
function filters(statuses) {return `<div class="filters"><input id="list-search" class="search" type="search" aria-label="Zoeken" placeholder="Zoek op naam, Discord-ID of dossier…" value="${e(state.search)}"><select id="list-status" aria-label="Status filteren"><option value="all">Alle statussen</option>${statuses.map(status=>`<option value="${status}" ${state.filter===status?'selected':''}>${e(labels[status]||status)}</option>`).join('')}</select></div>`;}
function caseTable(kind) {
  if(kind==='ticket'&&!state.data.guild.ticketsEnabled)return `<div class="notice">Gewone tickets zijn alleen ingeschakeld in de Legion Community-guild. Sollicitaties blijven hier beschikbaar.</div>${card('Ticketmodule','Voor deze server uitgeschakeld',empty('Selecteer Legion Community','Kies de community-server linksboven om vraagtickets te beheren.'))}`;
  const items=state.data.cases.filter(item=>item.kind===kind&&(state.filter==='all'||item.status===state.filter)&&`${item.owner_name} ${item.owner_id} ${item.id}`.toLowerCase().includes(state.search.toLowerCase()));
  const rows=items.map(item=>[person(item.owner_name,item.owner_id,item.owner_avatar),`<span class="mono">${e(item.id)}</span>`,badge(item.status),kind==='application'?(item.queue?`<span>${e(item.queue.stage)}</span><small class="muted"> · plek ${item.queue.position}/${item.queue.total}</small>`:item.dm_status?badge(item.dm_status):'<span class="muted">—</span>'):'<span class="muted">Privé kanaal</span>',e(date(item.created_at)),btn('Bekijken','case.open',`data-id="${e(item.id)}"`)]);
  let result=filters(['open','accepted','rejected','closed','failed'])+card(kind==='application'?'Sollicitatiedossiers':'Vraagtickets',`${items.length} weergegeven · nieuwste dossiers eerst`,table(['Aanvrager','Dossier','Status',kind==='application'?'Wachtstatus / DM':'Toegang','Aangemaakt',''],rows));
  if(kind==='application')result+=`<div class="grid equal" style="margin-top:20px">${quotaCard()}${card('Persoonlijke uitnodigingen','Automatisch bij aannemen',`<div class="card-body"><p class="quota-note">De ontvanger krijgt een groene aanname-DM met een link naar de gangserver. Discord bindt de uitnodiging aan zijn account.</p><div class="quota-footer"><span>1 gebruiker · 1 gebruik</span><span>Geldig: 24 uur</span></div><p class="muted" style="margin-top:13px">Na joinen vervalt de link. Geblokkeerde DM’s zijn hieronder zichtbaar; de sollicitant kan ook /uitnodiging gebruiken.</p></div>`)}</div>${card('Uitnodigingen & DM’s','Bezorgen, verlopen en opnieuw versturen',table(['Sollicitant','Status','Geldig tot',''],state.data.invitations.map(item=>[person(item.owner_name,item.owner_id),badge(item.status),e(date(item.expires_at)),item.status==='revoked'?'<span class="muted">Ingetrokken</span>':btn('DM opnieuw sturen','admission.resend',`data-id="${e(item.case_id)}"`)])))}`;
  return result;
}
function transcriptPage() {
  const items=state.data.transcripts.filter(item=>(state.filter==='all'||item.status===state.filter)&&`${item.owner_name} ${item.owner_id} ${item.id}`.toLowerCase().includes(state.search.toLowerCase()));
  return filters(['accepted','rejected','closed'])+card('Gesprekken terugvinden','Aangenomen, afgewezen en gesloten dossiers',table(['Aanvrager','Type','Status','Afgehandeld','Transcript'],items.map(item=>[person(item.owner_name,item.owner_id),item.kind==='application'?'Sollicitatie':'Vraag',badge(item.status),e(date(item.closed_at)),item.url?link('Transcript bekijken',item.url):badge(item.state||'unavailable')])));
}
function warningPage() {
  if(!state.data.guild.warningsEnabled)return '<div class="notice">Gangwarns worden in de hoofdserver van Legion beheerd. Selecteer die server om warns te geven of in te trekken.</div>'+card('Gangwarns','Voor deze guild niet ingesteld',empty('Selecteer de gangserver'));
  const items=state.data.warnings.filter(item=>(state.filter==='all'||(state.filter==='active'?!item.removed_at:!!item.removed_at))&&`${item.user_name} ${item.user_id} ${item.reason}`.toLowerCase().includes(state.search.toLowerCase()));
  return filters(['active','removed']).replace('>active<','>Actief<').replace('>removed<','>Ingetrokken<')+card('Gangwarns','Actieve warns en de volledige intrekhistorie',table(['Lid','Reden','Door','Status','Datum',''],items.map(item=>[person(item.user_name,item.user_id),`<span title="${e(item.reason)}">${e(item.reason.slice(0,70))}${item.reason.length>70?'…':''}</span>`,e(item.actor_name),item.removed_at?badge('revoked'):badge('open'),e(date(item.created_at)),item.removed_at?'<span class="muted">Historie</span>':btn('Intrekken','warn.remove',`data-id="${e(item.id)}"`)])));
}
function memberPage() {
  const items=state.data.members.filter(item=>`${item.name} ${item.id} ${item.rank||''}`.toLowerCase().includes(state.search.toLowerCase())&&(state.filter==='all'||(state.filter==='legion'?item.legion:!item.rank)));
  const ranks=[...new Set(state.data.members.filter(item=>item.rank).map(item=>item.rank))];
  return filters(['legion','no-rank']).replace('>legion<','>Legion-leden<').replace('>no-rank<','>Zonder rang<')+card('De mensen achter Legion',`${items.length} leden weergegeven`,table(['Lid','Hoogste rang','Legion','Coins',''],items.map(item=>[person(item.name,item.id,item.avatar),e(item.rank||'Zonder rang'),item.legion?'<span class="badge green">Lid</span>':'<span class="muted">Community</span>',item.coins===null?'<span class="muted">Nog niet gespeeld</span>':number(item.coins),btn('Coins bewerken','coins.edit',`data-user="${e(item.id)}"`)])))+`<div class="grid equal" style="margin-top:20px">${card('Rangverdeling','Elk lid staat bij de hoogste rang',`<div class="card-body rank-list">${ranks.length?ranks.map(rank=>`<div class="rank-row"><span>${e(rank)}</span><strong>${number(state.data.members.filter(item=>item.rank===rank).length)}</strong></div>`).join(''):empty('Geen gangrangen in deze guild','De ranglijst staat in de hoofdserver.')}</div>`)}${card('Automatische ledenlijst','Altijd gekoppeld aan Discord',`<div class="card-body"><p class="quota-note">Naam- en rolwijzigingen worden automatisch bijgewerkt. Handmatig vernieuwen controleert de hele ledenlijst.</p><div style="margin-top:18px">${state.data.roster?link('Ledenlijst in Discord',`https://discord.com/channels/${state.guild}/${state.data.roster.channelId}`):'<span class="muted">Selecteer de gangserver voor de ranglijst.</span>'}</div></div>`)}</div>`;
}
const field = (name,label,value,type='text',note='') => `<div class="field"><label for="field-${name}">${e(label)}</label><input id="field-${name}" name="${e(name)}" type="${type}" value="${e(value)}" required>${note?`<small>${e(note)}</small>`:''}</div>`;
function gameSettingsPage() {
  const s=state.data.settings;
  return `<div class="grid equal">${card('Coin-economie','Fictieve punten binnen Discord',`<form id="game-settings" class="card-body"><div class="form-grid">${field('startingCoins','Startsaldo',s.startingCoins,'number','Alleen voor nieuwe wallets.')}${field('dailyCoins','Dagelijkse beloning',s.dailyCoins,'number')}${field('maxBet','Maximale inzet',s.maxBet,'number')}${field('coinName','Naam van de coins',s.content.coinName)}</div><div class="field"><label for="game-access">Wie mag spelen?</label><select id="game-access" name="gamesMembersOnly"><option value="false" ${s.gamesMembersOnly?'':'selected'}>Iedereen in de server</option><option value="true" ${s.gamesMembersOnly?'selected':''}>Alleen Legion-leden en leiding</option></select><small>Fun-resultaten blijven openbaar in Discord.</small></div><div class="form-buttons"><button class="primary" type="submit">Instellingen opslaan</button></div></form>`)}${card('Leaderboard','De rijkste spelers van deze guild',table(['#','Speler','Coins'],state.data.leaderboard.map((item,index)=>[number(index+1),person(item.name,item.id),`<strong>${number(item.balance)}</strong>`])))}</div>${card('Fun-commands','Beschikbaar in Discord',`<div class="card-body command-list">${state.data.commands.filter(command=>['saldo','daily','leaderboard','blackjack','coinflip','dobbel','8ball','steenpapier','fish'].includes(command.name)).map(command=>`<div class="command"><code>/${e(command.name)}</code><p>${e(command.description)}</p></div>`).join('')}</div>`)}<div class="notice" style="margin-top:20px">Vissen beloont zeldzame vangsten en slechte vangsten kosten coins. Blackjack wordt groen bij winst, rood bij verlies en oranje bij gelijkspel.</div>`;
}
function informationPage() {
  const c=state.data.settings.content;
  return `<form id="information-settings">${card('Legion-identiteit','Deze teksten verschijnen in embeds en panelen',`<div class="card-body"><div class="form-grid">${field('gangName','Gangnaam',c.gangName)}${field('serverName','Roleplayserver',c.serverName)}</div>${field('tagline','Korte omschrijving',c.tagline)}<div class="field"><label for="info-text">Informatietekst</label><textarea id="info-text" name="information" class="large" required>${e(c.information)}</textarea></div></div>`)}<div class="grid equal" style="margin-top:20px">${card('Regels','Eén regel per lijn',`<div class="card-body field"><textarea name="rules" class="large" aria-label="Regels" required>${e(c.rules.join('\n'))}</textarea><small>Maximaal 20 regels, 150 tekens per regel.</small></div>`)}${card('Panelen & tickets','De introductie voor je community',`<div class="card-body"><div class="field"><label for="app-intro">Sollicitatie-intro</label><textarea id="app-intro" name="applicationIntro" required>${e(c.applicationIntro)}</textarea></div><div class="field"><label for="ticket-intro">Ticket-intro</label><textarea id="ticket-intro" name="ticketIntro" required>${e(c.ticketIntro)}</textarea></div><p class="muted">Sollicitaties en tickets openen altijd direct. Er worden geen intakeformulieren toegevoegd.</p></div>`)}</div><div class="form-buttons"><button class="primary" type="submit">Teksten opslaan</button></div></form>`;
}
function gamesPage() {
  const m=state.data.missions;
  return gameSettingsPage()+card('Dagelijkse fun-missies',`${m.day} · ${m.claimedToday} beloningen geclaimd`, `<div class="card-body">${m.definitions.map(mission=>`<div class="activity-row"><div class="activity-main"><strong>${e(mission.title)}</strong><p>${e(mission.description)}</p></div><span class="badge green">${mission.reward} coins</span></div>`).join('')}<p class="muted" style="margin-top:14px">Leden bekijken hun voortgang met /missies. Nieuwe missies starten om 00:00 Belgische tijd. Een beloning kan één keer per missie en dag worden geclaimd.</p></div>`);
}
function planningPage() {
  if(!state.data.planningChannelId)return card('Planning in de gangserver','Selecteer Legion om activiteiten te beheren',empty('Alleen in de gangserver','De planning wordt in het vaste Legion-planningkanaal geplaatst.'));
  const items=state.data.plannings.filter(item=>`${item.title} ${item.location}`.toLowerCase().includes(state.search.toLowerCase()));
  return `<div class="notice">Maak een planning in Discord met <strong>/planning datum tijd afspreekpunt</strong>. De bot plaatst een tekstbericht met voorbereiding en vier emoji-reacties in het vaste gangkanaal.</div>`+card('Activiteitenkalender','Iedereen kan één aanwezigheidskeuze maken',table(['Activiteit','Wanneer','Afspreekpunt','Aanwezigheid','Status',''],items.map(item=>[e(item.title),e(date(item.starts_at)),e(item.location),['🟢','🕒','🔴','🟠'].map((emoji,i)=>`${emoji} ${item.participants.filter(person=>person.response===['yes','late','no','maybe'][i]).length}`).join(' · '),badge(item.status),`${item.url?link('Bericht',item.url):'<span class="muted">Wordt geplaatst</span>'}${item.status==='open'?btn('Annuleren','planning.cancel',`data-id="${e(item.id)}"`,'danger'):''}`])))+card('Wie heeft gereageerd?','De opgeslagen aanwezigheidskeuzes',table(['Activiteit','Lid','Keuze'],items.flatMap(item=>item.participants.map(person=>[e(item.title),e(person.name),e({yes:'🟢 Ik ben erbij',late:'🕒 Ik ben later',no:'🔴 Ik ben er niet bij',maybe:'🟠 Ik weet het nog niet zeker'}[person.response])]))));
}
function promotionsPage() {
  if(!state.data.roster)return card('Gangrangen','Promoties worden in de gangserver beheerd',empty('Selecteer Legion','De community-server heeft geen gangrangen voor promotievoorstellen.'));
  const items=state.data.promotions.filter(item=>`${item.member_name} ${item.role_name} ${item.reason}`.toLowerCase().includes(state.search.toLowerCase()));
  return `<div class="notice">Maak een voorstel met <strong>/promotie lid rang motivatie</strong>. Alleen leden met de Lead-rol kunnen stemmen. Vanaf <strong>drie verschillende Lead-stemmen</strong> bepaalt de meerderheid de uitslag. Tot die tijd kun je je eigen stem aanpassen.${state.data.canVotePromotions?'':' Je hebt de Lead-rol nodig om hier te stemmen.'}</div>`+card('Promotievoorstellen','De meerderheid beslist; andere rollen blijven behouden',table(['Lid','Voorgestelde rang','Motivatie','Stemmen','Status',''],items.map(item=>{const votes=item.voting||{approve:0,reject:0,total:0};const attrs=`data-id="${e(item.id)}"${state.data.canVotePromotions?'':' disabled'}`;return[e(item.member_name),e(item.role_name),`<span title="${e(item.reason)}">${e(item.reason.slice(0,90))}</span>`,`🟢 ${votes.approve} · 🔴 ${votes.reject}<small class="muted"> · ${votes.total} Lead-stemmen</small>`,badge(item.status),`${item.url?link('Voorstel',item.url):''}${item.status==='pending'?btn('Goedkeuren','promotion.approve',attrs,'primary')+btn('Afkeuren','promotion.reject',attrs,'danger'):''}`];})));
}
function settingsPage() {
  const d=state.data,s=d.settings;
  return `<div class="grid equal">${card('Gangbeheer','Afspraken voor deze server',`<form id="general-settings" class="card-body">${field('warnThreshold','Warn-drempel',s.warnThreshold,'number','Vanaf dit aantal krijgt de leiding een extra melding.')}<div class="field"><label>Leidingrollen</label><input value="${e(d.guild.staffRoleNames.join(', '))}" disabled><small>Toegangsrollen worden door een administrator in Discord beheerd.</small></div><div class="field"><label>Sollicitatiecapaciteit</label><input value="25 plaatsen · beperkte plaatsen vanaf 20 · leeftijd 16+" disabled></div><div class="form-buttons"><button class="primary" type="submit">Opslaan</button></div></form>`)}${card('Discord-panelen','Je bestaande panelen blijven gekoppeld',`<div class="card-body">${d.panels.length?d.panels.map(panel=>`<div class="activity-row"><div class="activity-main"><strong>${e(panel.type==='alles'?'Tickets & solliciteren':panel.type)}</strong><p>Kanaal ${e(panel.channelId)}</p></div>${link('Openen',panel.url)}</div>`).join(''):empty('Geen paneel ingesteld','Plaats een paneel via /setup in Discord.')}<div style="margin-top:18px">${btn('Panelen vernieuwen','panel.refresh')}</div></div>`)}</div>${card('Hosting & opslag','Voor verhuizen of herstarten',`<div class="card-body"><div class="stats-inline"><div><strong>Node.js 24</strong><span>Aanbevolen runtime</span></div><div><strong>data/</strong><span>Blijvende botgegevens</span></div></div><p class="quota-note">Het dashboard, de transcripts en de bot starten samen via index.js. Neem bij een verhuizing de hele data-map en je private .env mee. De hosting moet deze data-map bij herstarten bewaren.</p><p class="muted" style="margin-top:13px">Na een nieuw tunneladres werken de transcriptknoppen automatisch bij. Een nieuwe dashboardlink krijg je via /dashboard.</p></div>`)}`;
}
function gangpotPage(){
  const d=state.data.gangpot;
  if(!d)return card('Gangpot in de hoofdserver','Selecteer Legion om de gangpot te beheren',empty('Alleen in de gangserver','In de community-server worden geen gangpotbijdragen bijgehouden.'));
  const money=value=>'$'+number(value),pending=d.claims.filter(item=>item.status==='pending');
  const status={paid:'🟢 Tijdig goedgekeurd',warned:'🔴 Gangwarn',late:'🟠 Te laat goedgekeurd',partial:'🟠 Gedeeltelijk',unpaid:'🟠 Geen goedkeuring',left:'Vertrokken',exempt:'✅ Vrijgesteld'};
  return `<div class="notice">Leden gebruiken <strong>/gangpot betaling</strong>. Alleen Lead kan ✅ goedkeuren of ❌ afkeuren. Iedere zaterdag om <strong>23:59 Belgische tijd</strong> volgt automatisch één gangwarn voor leden zonder volledige goedkeuring. Ook wachten op controle geeft geen uitstel.</div>`+
    card('Bevestigde gangpot',d.period?`Huidige termijn t/m ${d.period.id}`:'De eerste termijn wordt gestart',`<div class="card-body"><div class="stats-inline"><div><strong>${money(d.balance)}</strong><span>Saldo in-game</span></div><div><strong>${money(d.weeklyAmount)}</strong><span>Per lid per week</span></div><div><strong>${pending.length}</strong><span>Wachten op Lead</span></div></div><div class="table-actions" style="margin-top:18px">${btn('Donatie registreren','gangpot.new-donation')}${btn('Uitgave registreren','gangpot.new-expense')}</div></div>`)+
    card('Betaalmeldingen','Een vinkje telt pas vanaf het moment van goedkeuring',table(['Lid','Termijn','Bedrag','Toelichting','Status',''],d.claims.map(item=>[e(item.userName),e(item.period_id),money(item.amount),e(item.note),badge(item.status),`${item.url?link('Discord',item.url):''}${item.status==='pending'?btn('✅ Goedkeuren','gangpot.approve',`data-id="${e(item.id)}"${state.data.canReviewGangpot?'':' disabled'}`,'primary')+btn('❌ Afkeuren','gangpot.reject',`data-id="${e(item.id)}"${state.data.canReviewGangpot?'':' disabled'}`,'danger'):e(item.reviewerName||'')}`])))+
    card('Weekbijdragen','Alleen leden met de Legion-ledenrol · zaterdag–zaterdag',table(['Lid','Goedgekeurd','Nog open','Status'],d.members.filter(item=>item.active).map(item=>[e(item.name),money(item.paid),money(item.remaining),e(status[item.status]||item.status)])))+
    card('Transactiehistorie','Correcties blijven zichtbaar; fun-coins staan hier los van',table(['ID','Soort','Bedrag','Lid / leiding','Datum','Notitie',''],d.entries.map(item=>[e(item.id),e({payment:'Weekbijdrage',donation:'Donatie',expense:'Uitgave'}[item.kind]),money(item.amount),e(item.userName||item.actorName),e(date(item.created_at)),e(item.note),item.voided_at?badge('revoked'):btn('Corrigeren','gangpot.void-form',`data-id="${e(item.id)}"`,'danger')])));
}
function renderPage() {
  if(!state.data)return;navigation();const [title,description]=pages[state.page];$('#breadcrumb').textContent=title;$('#page-title').textContent=title;$('#page-description').textContent=description;$('#eyebrow').textContent=state.data.guild.name.toUpperCase();
  $('#page-actions').innerHTML=state.page==='warnings'&&state.data.guild.warningsEnabled?'<button class="primary" type="button" data-action="warn.new">+ Gangwarn geven</button>':state.page==='members'?'<button class="secondary" type="button" data-action="members.refresh">Leden synchroniseren ↻</button>':state.page==='applications'||state.page==='tickets'?'<button class="secondary" type="button" data-action="panel.refresh">Discord-paneel bijwerken</button>':'';
  const renderers={overview,tickets:()=>caseTable('ticket'),applications:()=>caseTable('application'),transcripts:transcriptPage,warnings:warningPage,members:memberPage,games:gamesPage,planning:()=>planningPage()+planningAbsencesPage(),promotions:promotionsPage,gangpot:gangpotPage,absences:absencesPage,health:healthPage,modules:modulesPage,collection:collectionPage,information:informationPage,settings:settingsPage,activity:()=>card('Activiteitenlog','Commands, knoppen, dashboardacties en servergebeurtenissen',`<div class="card-body">${activityRows(state.data.activity)}<div class="form-buttons">${btn('Oudere logs laden','logs.more')}</div></div>`)};
  $('#content').innerHTML=renderers[state.page]();bindForms();
}
function selectPage(page) { if(!pages[page])return;state.page=page;state.search='';state.filter='all';renderPage();document.body.classList.remove('menu-open');window.scrollTo({top:0,behavior:'smooth'}); }
async function action(value) { if(state.busy)return;state.busy=true;$('#app').classList.add('busy');try{const result=await api(`/api/dashboard/guilds/${state.guild}/actions`,value);toast(result.message);await load();return result;}catch(error){if(error.status===401||error.status===403)showLogin(error.message);else toast(error.message,true);throw error;}finally{state.busy=false;$('#app').classList.remove('busy');} }
function openDialog(html) {$('#dialog-content').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function confirmAction(message) {
  const dialog=$('#dialog'),previous=$('#dialog-content').innerHTML,restore=dialog.open;
  return new Promise(resolve=>{
    let finished=false;
    const finish=accepted=>{if(finished)return;finished=true;dialog.removeEventListener('close',closed);dialog.removeEventListener('cancel',cancelled);dialog.close();if(!accepted&&restore)openDialog(previous);resolve(accepted);};
    const closed=()=>finish(false),cancelled=event=>{event.preventDefault();finish(false);};
    openDialog(`<h2>Actie bevestigen</h2><p style="margin:14px 0 24px;color:var(--muted)">${e(message)}</p><div class="form-buttons"><button id="confirmation-no" type="button" class="secondary">Annuleren</button><button id="confirmation-yes" type="button" class="primary">Bevestigen</button></div>`);
    $('#confirmation-no').addEventListener('click',()=>finish(false));$('#confirmation-yes').addEventListener('click',()=>finish(true));dialog.addEventListener('close',closed);dialog.addEventListener('cancel',cancelled);
  });
}
async function openCase(id) {
  const item=state.data.cases.find(item=>item.id===id);if(!item)return;
  const transcript=state.data.transcripts.find(item=>item.id===id);
  openDialog(`<div class="case-detail"><span class="eyebrow">${item.kind==='application'?'SOLLICITATIE':'VRAAGTICKET'}</span><h2>${e(item.owner_name)}</h2><p class="meta">Dossier ${e(id)} · ${e(date(item.created_at))}</p><div class="status-line">${badge(item.status)}${item.dm_status?badge(item.dm_status):''}</div>${item.status==='open'?`<div class="table-actions">${item.kind==='application'?`${btn('Gesprek starten','case.interview',`data-id="${e(id)}"`)}${btn('Aannemen','case.accept',`data-id="${e(id)}"`,'primary')}${btn('Afwijzen','case.reject',`data-id="${e(id)}"`,'danger')}`:''}${btn('Sluiten','case.close',`data-id="${e(id)}"`,'danger')}</div><p class="muted" style="margin-top:13px">${item.kind==='application'?'Controleer de antwoorden en de minimumleeftijd van 16 jaar voordat je aanneemt.':'Na sluiten wordt het transcript opgeslagen en het kanaal verwijderd.'}</p>`:transcript?.url?link('Volledig transcript bekijken',transcript.url,'primary'):'<div class="notice">Het originele kanaal is afgehandeld. Bekijk de exportstatus bij Transcripts.</div>'}<div id="case-messages"><p class="muted" style="margin-top:20px">Gesprek wordt geladen…</p></div></div>`);
  try{const result=await api(`/api/dashboard/guilds/${state.guild}/cases/${id}/messages`);if(!$('#case-messages'))return;$('#case-messages').innerHTML=result.messages.length?result.messages.map(message=>`<article class="message"><strong>${e(message.author)}</strong><time>${e(date(message.created))}</time>${message.content?`<pre>${e(message.content)}</pre>`:''}${message.embeds.map(card=>`<div class="message-embed">${card.title?`<strong>${e(card.title)}</strong>\n`:''}${e(card.description||'')}${(card.fields||[]).map(field=>`\n\n${e(field.name)}\n${e(field.value)}`).join('')}</div>`).join('')}${message.attachments.map(file=>{let valid=false;try{valid=new URL(file.url).protocol==='https:';}catch{}return valid?`<p style="margin-top:8px">${link(file.name,file.url)}</p>`:'';}).join('')}</article>`).join(''):result.closed?'':empty('Nog geen berichten');}catch(error){if($('#case-messages'))$('#case-messages').textContent=error.message;}
}
function userSelect(selected='') { return `<select name="userId" aria-label="Legion-lid" required><option value="">Kies een lid…</option>${state.data.members.map(member=>`<option value="${e(member.id)}" ${member.id===selected?'selected':''}>${e(member.name)}</option>`).join('')}</select>`; }
function warningForm(id) { const remove=Boolean(id);openDialog(`<h2>${remove?'Gangwarn intrekken':'Gangwarn geven'}</h2><p class="meta muted" style="margin:8px 0 20px">${remove?'De originele warn blijft in de historie.':'Het lid en de leiding zien de gangwarn in het ingestelde kanaal.'}</p><form id="warning-form">${remove?'':`<div class="field"><label>Lid</label>${userSelect()}</div>`}<div class="field"><label for="warn-reason">Reden</label><textarea id="warn-reason" name="reason" maxlength="500" required></textarea></div><div class="form-buttons"><button class="${remove?'danger':'primary'}" type="submit">${remove?'Warn intrekken':'Warn geven'}</button></div></form>`);$('#warning-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.target);try{await action({action:remove?'warn.remove':'warn.add',...(remove?{id}:{userId:form.get('userId')}),reason:form.get('reason')});$('#dialog').close();}catch{}}); }
function coinsForm(user) {const member=state.data.members.find(member=>member.id===user);if(!member)return;openDialog(`<h2>Coins bewerken</h2><p class="muted" style="margin:7px 0 20px">${e(member.name)} · saldo ${number(member.coins??state.data.settings.startingCoins)} ${e(state.data.settings.content.coinName)}</p><form id="coin-form">${field('amount','Toevoegen of afhalen',0,'number','Gebruik een negatief bedrag om coins af te halen.')}<div class="field"><label for="coin-reason">Reden</label><textarea id="coin-reason" name="reason" maxlength="500" required></textarea></div><div class="form-buttons"><button class="primary" type="submit">Saldo bijwerken</button></div></form>`);$('#coin-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.target);try{await action({action:'coins.adjust',userId:user,amount:Number(form.get('amount')),reason:form.get('reason')});$('#dialog').close();}catch{}});}
function bindForms() {
  bindModuleForms();
  $('#list-search')?.addEventListener('input',event=>{state.search=event.target.value;const cursor=event.target.selectionStart;renderPage();$('#list-search')?.focus();$('#list-search')?.setSelectionRange(cursor,cursor);});
  $('#list-status')?.addEventListener('change',event=>{state.filter=event.target.value;renderPage();});
  $('#game-settings')?.addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.target);try{await action({action:'settings.save',settings:{startingCoins:Number(f.get('startingCoins')),dailyCoins:Number(f.get('dailyCoins')),maxBet:Number(f.get('maxBet')),gamesMembersOnly:f.get('gamesMembersOnly')==='true',content:{coinName:f.get('coinName')}}});}catch{}});
  $('#general-settings')?.addEventListener('submit',async event=>{event.preventDefault();try{await action({action:'settings.save',settings:{warnThreshold:Number(new FormData(event.target).get('warnThreshold'))}});}catch{}});
  $('#information-settings')?.addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.target);try{await action({action:'settings.save',settings:{content:{gangName:f.get('gangName'),serverName:f.get('serverName'),tagline:f.get('tagline'),information:f.get('information'),rules:String(f.get('rules')).split('\n').map(rule=>rule.trim()).filter(Boolean),applicationIntro:f.get('applicationIntro'),ticketIntro:f.get('ticketIntro')}}});}catch{}});
}
function gangpotForm(kind,id){
  const correction=kind==='void';
  openDialog(`<h2>${correction?'Gangpotregistratie corrigeren':kind==='donation'?'Donatie registreren':'Uitgave registreren'}</h2><p class="muted" style="margin:12px 0 20px">Registreer alleen werkelijk ontvangen of uitgegeven FiveM-geld. De historie blijft bewaard.</p><form id="gangpot-form">${correction?'':field('amount','Bedrag in-game',25000,'number')}<div class="field"><label for="gangpot-note">${correction?'Reden':'Toelichting'}</label><textarea name="note" id="gangpot-note" required maxlength="500"></textarea></div><div class="form-buttons"><button class="primary" type="submit">Registreren</button></div></form>`);
  $('#gangpot-form').addEventListener('submit',async event=>{
    event.preventDefault();const form=new FormData(event.target),note=form.get('note'),amount=Number(form.get('amount'));
    if(!await confirmAction(correction?'Wil je deze registratie corrigeren? Het saldo en eventuele gangpotwarn worden opnieuw berekend.':`Bevestig dat dit bedrag werkelijk ${kind==='donation'?'ontvangen':'uitgegeven'} is: $${number(amount)}.`)){gangpotForm(kind,id);$('#gangpot-note').value=note;const input=$('#gangpot-form [name="amount"]');if(input)input.value=amount;return;}
    try{await action({action:`gangpot.${kind}`,id,amount,note,reason:note,requestId:crypto.randomUUID(),confirm:true});$('#dialog').close();}catch{}
  });
}
function healthPage(){const h=state.data.health;return card('Verbinding',h.ready?'Online':'Starten of herstellen',`<div class="card-body stats-inline"><div><strong>${number(Math.floor(h.uptime/60))} min</strong><span>Uptime</span></div><div><strong>${number(h.latency)} ms</strong><span>Vertraging</span></div><div><strong>${number(h.memoryMB)} MB</strong><span>Geheugen</span></div></div>`)+card('Wachtrijen','Deze acties worden automatisch opnieuw geprobeerd',table(['Onderdeel','Aantal'],Object.entries(h.counts).map(([key,n])=>[e(key),number(n)])))+card('Geregistreerde problemen','Foutcodes zonder tokens of privé-inhoud',table(['Onderdeel','Foutcode'],h.errors.map(item=>[e(item.module),e(item.code)])));}
function absencesPage(){if(!state.data.gangpot)return empty('Alleen in de hoofdserver');const lead=state.data.canReviewGangpot;return `<div class="notice">Leden vragen afwezigheid aan met /afwezig aanvragen, of melden zich voor een planning af met /afmelden. Alleen Lead kan goedkeuren. Een rode reactie telt pas na goedkeuring.</div><div class="form-buttons">${btn('Afwezigheid aanvragen','absence.new')}${btn('Weekvrijstelling geven','absence.exempt-new',lead?'':'disabled')}</div>`+card('Afmeldingen','Redenen zijn alleen zichtbaar voor de leiding',table(['Lid','Periode / planning','Weken','Reden','Status',''],state.data.absences.map(item=>[e(item.userName),e(item.activity_id||`${item.start_date} t/m ${item.end_date}`),e(item.weeks.join(', ')),e(item.reason),badge(item.status),item.status==='pending'?btn('Goedkeuren','absence.approve',`data-id="${e(item.id)}"${lead?'':' disabled'}`,'primary')+btn('Afwijzen','absence.reject',`data-id="${e(item.id)}"${lead?'':' disabled'}`,'danger'):e(item.reviewerName)])))+card('Gangpotvrijstellingen','Een vrijstelling geldt uitsluitend voor de genoemde week',table(['Lid','Week','Status',''],state.data.exemptions.map(item=>[e(item.userName),e(item.period_id),item.revoked_at?badge('revoked'):badge('approved'),item.revoked_at?'':btn('Intrekken','absence.revoke-form',`data-user="${e(item.user_id)}" data-week="${e(item.period_id)}"${lead?'':' disabled'}`,'danger')])));}
function planningAbsencesPage(){if(!state.data.planningChannelId)return'';return `<div class="form-buttons">${btn('Planning maken','planning.new')}</div>`+card('Afmeldingen bij activiteiten','Alleen goedgekeurde afmeldingen geven toestemming om afwezig te zijn',table(['Activiteit','Lid','Status'],state.data.plannings.flatMap(item=>(item.absences||[]).map(person=>[e(item.title),e(person.name),badge(person.status)]))));}
function collectionPage(){return card('Visverzamelingen','Leden bekijken hun eigen vangsten en challenges met /vangstenboek',table(['Lid','Vangst','Aantal'],state.data.fishCollections.map(item=>[e(item.userName),e(item.catch_name||item.catch_id),number(item.amount)])))+`<div class="notice">De standaard weekchallenges belonen goede en zeldzame vangsten. Beloningen en aantallen zijn aanpasbaar bij Modules instellen. De waarden voor een al begonnen challengeweek blijven bewaard.</div>`;}
const operationLabels={gangpot:'Gangpot & herinneringen',planning:'Planning',fishing:'Visverzameling & weekchallenges',absence:'Afwezigheid',logs:'Botlogs',recruitment:'Sollicitaties',admission:'Persoonlijke uitnodigingen'};
const settingLabels={weeklyAmount:'Weekbijdrage in-game',deadlineTime:'Deadline op zaterdag',remindersEnabled:'Herinneringen voor leden',fridayTime:'Vrijdag: DM-tijd',saturdayTime:'Zaterdag: DM-tijd',leadReminderEnabled:'Overzicht voor Lead',leadTime:'Zaterdag: Lead-tijd',requireApproval:'Afmelding vereist Lead-goedkeuring',duration:'Standaard duur (minuten)',title:'Standaard activiteitnaam',preparation:'Voorbereiding',collectionEnabled:'Verzameling bijhouden',weeklyEnabled:'Weekchallenges',target:'Goede vangsten nodig',rareTarget:'Zeldzame vangsten nodig',reward:'Coins voor goede vangsten',rareReward:'Coins voor zeldzame vangsten',maxDays:'Maximale afwezigheid (dagen)',enabled:'Logs naar Discord',batchSize:'Gebeurtenissen per logbericht',capacity:'Sollicitatiecapaciteit',limitedAt:'Oranje vanaf dit aantal',minimumAge:'Minimumleeftijd',inviteMaxAgeSeconds:'Invite geldig (seconden)'};
function modulesPage(){const d=state.data;let html='<div class="notice">Alle tijden zijn Belgisch. Gangpotbedrag en deadline gelden standaard vanaf de volgende week; vink hieronder aan als je ook de lopende week wilt wijzigen. Visbeloningen gelden vanaf een nieuwe challengeweek.</div><form id="module-settings">';for(const [group,settings]of Object.entries(d.operations)){if((group==='gangpot'||group==='absence')&&!d.gangpot)continue;if(group==='recruitment'&&!d.guild.ticketsEnabled)continue;html+=card(operationLabels[group],'Instellingen voor deze server',`<div class="card-body form-grid">${Object.entries(settings).map(([key,value])=>{const name=`${group}.${key}`,label=settingLabels[key]||key;if(typeof value==='boolean')return`<div class="field"><label>${e(label)}</label><select name="${e(name)}"><option value="true" ${value?'selected':''}>Aan</option><option value="false" ${value?'':'selected'}>Uit</option></select></div>`;if(key==='preparation')return`<div class="field"><label>${e(label)}</label><textarea name="${e(name)}" maxlength="700">${e(value)}</textarea></div>`;return field(name,label,value,typeof value==='number'?'number':key.endsWith('Time')?'time':'text');}).join('')}</div>`);}html+=`<div class="card-body">${field('embedColor','Embedkleur',d.embedColor,'color')}${d.gangpot?'<label><input name="applyCurrent" type="checkbox"> Pas gangpotbedrag en deadline ook toe op de lopende week</label>':''}<div class="form-buttons"><button class="primary" type="submit">Module-instellingen opslaan</button></div></div></form>`;
  if(d.canConfigureChannels)html+=`<form id="channel-settings">${card('Bestemmingskanalen','Alleen administrators kunnen kanalen wijzigen',`<div class="card-body form-grid">${Object.entries(d.channelSettings).filter(([,id])=>id).map(([key,id])=>`<div class="field"><label>${e({logChannelId:'Privé leidinglog',botLogChannelId:'Botlogs',updateChannelId:'Changelog',absencePanelChannelId:'Afmeldpaneel',planningChannelId:'Planning',warnLogChannelId:'Gangwarns',panelChannelId:'Communitypaneel',gangpotInfo:'Gangpotinformatie',gangpotPayments:'Betaalmeldingen',gangpotTotal:'Totaal gangpot'}[key]||key)}</label><select name="${e(key)}">${d.channels.map(channel=>`<option value="${e(channel.id)}" ${channel.id===id?'selected':''}>${e(channel.name)}</option>`).join('')}</select></div>`).join('')}</div>`)}<div class="form-buttons"><button class="primary" type="submit">Kanalen opslaan</button></div></form>`;
  return html;
}
function bindModuleForms(){
  $('#module-settings')?.addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.target),operations={};for(const [group,settings]of Object.entries(state.data.operations)){for(const [key,value]of Object.entries(settings)){const input=form.get(`${group}.${key}`);if(input===null)continue;(operations[group]||={})[key]=typeof value==='boolean'?input==='true':typeof value==='number'?Number(input):input;}}const current=form.get('applyCurrent')==='on';if(current&&!await confirmAction('Wil je ook de lopende gangpotweek wijzigen? Het openstaande bedrag en de deadline van deze week veranderen.'))return;try{await action({action:'settings.save',settings:{operations,color:form.get('embedColor')},applyCurrent:current,confirm:current});}catch{}});
  $('#channel-settings')?.addEventListener('submit',async event=>{event.preventDefault();try{await action({action:'settings.save',settings:{channels:Object.fromEntries(new FormData(event.target))}});}catch{}});
}
function planningForm(){openDialog(`<h2>Planning maken</h2><form id="new-planning">${field('date','Datum, deze avond of morgenavond','morgenavond')}${field('time','Tijd','20:00','time')}${field('location','Afspreekpunt','Legion HQ')}${field('title','Activiteit',state.data.operations.planning.title)}${field('duration','Duur (minuten)',state.data.operations.planning.duration,'number')}<div class="form-buttons"><button class="primary" type="submit">Plaatsen</button></div></form>`);$('#new-planning').addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));values.duration=Number(values.duration);try{await action({action:'planning.create',...values});$('#dialog').close();}catch{}});}
function absenceForm(){openDialog(`<h2>Afwezigheid aanvragen</h2><form id="new-absence">${field('start','Vanaf','', 'date')}${field('end','Tot en met','', 'date')}<div class="field"><label>Reden</label><textarea name="reason" required maxlength="500"></textarea></div><div class="form-buttons"><button class="primary" type="submit">Aanvragen</button></div></form>`);$('#new-absence').addEventListener('submit',async event=>{event.preventDefault();try{await action({action:'absence.request',...Object.fromEntries(new FormData(event.target))});$('#dialog').close();}catch{}});}
function exemptionForm(user='',week='',revoke=false){openDialog(`<h2>${revoke?'Vrijstelling intrekken':'Weekvrijstelling geven'}</h2><form id="exemption-form">${user?'':userSelect()}${field('week','Zaterdag van de week (DD-MM-JJJJ)',week)}<div class="field"><label>Reden</label><textarea name="reason" required maxlength="500"></textarea></div><div class="form-buttons"><button class="primary" type="submit">Opslaan</button></div></form>`);$('#exemption-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.target);try{await action({action:revoke?'absence.revoke':'absence.exempt',userId:user||form.get('userId'),week:form.get('week'),reason:form.get('reason')});$('#dialog').close();}catch{}});}
document.addEventListener('click',async event=>{
  const target=event.target.closest('[data-page],[data-action]');if(!target)return;
  if(target.dataset.page){selectPage(target.dataset.page);return;}
  const name=target.dataset.action,id=target.dataset.id;
  try{
    if(name==='logs.more'){const before=Math.min(...state.data.activity.map(item=>item.id));const result=await api(`/api/dashboard/guilds/${state.guild}/audit?before=${before}`);state.data.activity.push(...result.items);renderPage();return;}
    if(name==='planning.new')return planningForm();
    if(name==='absence.new')return absenceForm();
    if(name==='absence.exempt-new')return exemptionForm();
    if(name==='absence.revoke-form')return exemptionForm(target.dataset.user,target.dataset.week,true);
    if(name==='absence.approve'||name==='absence.reject'){if(!await confirmAction(name==='absence.approve'?'Wil je deze afmelding goedkeuren? Bij een vakantieaanvraag worden de genoemde gangpotweken vrijgesteld.':'Wil je deze afmelding afwijzen?'))return;await action({action:name,id,confirm:true});return;}
    if(name==='case.open')return await openCase(id);
    if(name==='warn.new')return warningForm();
    if(name==='warn.remove')return warningForm(id);
    if(name==='coins.edit')return coinsForm(target.dataset.user);
    if(name==='gangpot.new-donation')return gangpotForm('donation');
    if(name==='gangpot.new-expense')return gangpotForm('expense');
    if(name==='gangpot.void-form')return gangpotForm('void',id);
    if(name==='gangpot.approve'||name==='gangpot.reject'){
      if(!await confirmAction(name==='gangpot.approve'?'Is deze betaling werkelijk in-game ontvangen? Het vinkje geldt vanaf nu; een goedkeuring na de deadline verwijdert een gangwarn niet.':'Wil je deze betaalmelding afkeuren? Het lid krijgt geen vinkje en de deadline blijft gelden.'))return;
      await action({action:name,id,confirm:true});return;
    }
    if(name==='planning.cancel'||name==='promotion.approve'||name==='promotion.reject') {
      const question=name==='planning.cancel'?'Wil je deze planning annuleren? Er worden daarna geen nieuwe aanwezigheidskeuzes verwerkt.':name==='promotion.approve'?'Wil je stemmen voor deze promotie? Vanaf drie unieke Lead-stemmen bepaalt de meerderheid de uitslag.':'Wil je stemmen tegen deze promotie? Vanaf drie unieke Lead-stemmen bepaalt de meerderheid de uitslag.';
      if(!await confirmAction(question))return;await action({action:name,id,confirm:true});return;
    }
    if(name.startsWith('case.')){const verb={'case.accept':'aannemen','case.reject':'afwijzen','case.close':'sluiten','case.interview':'een gesprek starten voor'}[name];if(!await confirmAction(`Wil je dit dossier ${verb}?${name==='case.accept'?' Controleer de minimumleeftijd van 16 jaar. De sollicitant krijgt een persoonlijke uitnodiging in DM.':name==='case.close'||name==='case.reject'?' Na de export wordt het kanaal verwijderd.':''}`))return;await action({action:name==='case.interview'?'case.interview':'case.decision',id,decision:name.split('.')[1],confirm:true});$('#dialog').close();return;}
    if(name==='admission.resend'&&!await confirmAction('Wil je het aannamebericht opnieuw versturen? De vorige uitnodiging wordt ingetrokken.'))return;
    await action({action:name,...(id?{id}:{})});
  }catch(error){if(!state.busy)toast(error.message,true);}
});
$('#guild-select').addEventListener('change',async event=>{state.guild=event.target.value;state.search='';state.filter='all';$('#dialog').close();try{await load();}catch(error){toast(error.message,true);}});
$('#menu').addEventListener('click',()=>document.body.classList.toggle('menu-open'));
$('#dialog-close').addEventListener('click',()=>$('#dialog').close());
$('#refresh').addEventListener('click',async()=>{try{await load();toast('Dashboard bijgewerkt.');}catch(error){toast(error.message,true);}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/dashboard/logout',{});}catch{}showLogin('Je bent uitgelogd. Gebruik /dashboard voor een nieuwe persoonlijke link.');});
setInterval(async()=>{if(!state.session||state.busy||$('#dialog').open)return;try{await load(!['settings','information','games'].includes(state.page));}catch(error){if(error.status===401||error.status===403)showLogin(error.message);else $('#connection').textContent='Verbinding controleren…';}},30000);
await boot();
